// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVQo5UCjCjnIgS8hzXzRi75WbNIQcIm7A',
    appId: '1:759707120454:web:782a961e6dc481c7b6eb47',
    messagingSenderId: '759707120454',
    projectId: 'bustracker-eabea',
    authDomain: 'bustracker-eabea.firebaseapp.com',
    storageBucket: 'bustracker-eabea.firebasestorage.app',
    measurementId: 'G-Y2M9RE81H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANOGOIdQ-fM5X6y63KaOvJltLIa8PGfkk',
    appId: '1:759707120454:android:b8bb282b3ad6ee88b6eb47',
    messagingSenderId: '759707120454',
    projectId: 'bustracker-eabea',
    storageBucket: 'bustracker-eabea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYobt2U9ErLSDqoh9Ru_bgBgOsVHzXTWo',
    appId: '1:759707120454:ios:b2a64d72669e092eb6eb47',
    messagingSenderId: '759707120454',
    projectId: 'bustracker-eabea',
    storageBucket: 'bustracker-eabea.firebasestorage.app',
    iosBundleId: 'com.example.busTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYobt2U9ErLSDqoh9Ru_bgBgOsVHzXTWo',
    appId: '1:759707120454:ios:b2a64d72669e092eb6eb47',
    messagingSenderId: '759707120454',
    projectId: 'bustracker-eabea',
    storageBucket: 'bustracker-eabea.firebasestorage.app',
    iosBundleId: 'com.example.busTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVQo5UCjCjnIgS8hzXzRi75WbNIQcIm7A',
    appId: '1:759707120454:web:9a1d02b5b4000210b6eb47',
    messagingSenderId: '759707120454',
    projectId: 'bustracker-eabea',
    authDomain: 'bustracker-eabea.firebaseapp.com',
    storageBucket: 'bustracker-eabea.firebasestorage.app',
    measurementId: 'G-Z3FWDD3PEE',
  );
}
